Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CertificatesManager.Database;
using CertificatesManager.Models;
using AutoMapper;
using CertificatesManager.ViewModels;

namespace CertificatesManager.Controllers
{
	public class GroupsController : Controller
	{
		private readonly CertificatesManagerDBContext _context;
		private readonly IMapper _mapper;


		public GroupsController(CertificatesManagerDBContext context, IMapper mapper)
		{
			_context = context;
			_mapper = mapper;
		}

		// GET: Groups
		public async Task<IActionResult> Index()
		{
			var group = await _context.Group
				.Include(x => x.Users)
					.ThenInclude(y => y.User)
				.ToListAsync();
			List<GroupViewModel> viewModels = _mapper.Map<List<GroupViewModel>>(group);
			return View(viewModels);
		}

		// GET: Groups/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var @group = await _context.Group
				.Include(x => x.Users)
					.ThenInclude(y => y.User)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (@group == null)
			{
				return NotFound();
			}
			GroupViewModel viewModel = _mapper.Map<GroupViewModel>(@group);
			return View(viewModel);
		}

		// GET: Groups/Create
		public IActionResult Create()
		{
			var viewModel = new GroupViewModel();
			LoadFieldsViewModel(viewModel);
			return View(viewModel);
		}

		// POST: Groups/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name, UserIds")] GroupViewModel groupViewModel)
		{
			if (ModelState.IsValid)
			{
				Group group = _mapper.Map<Group>(groupViewModel);
				PopulateModelWithSelectedValues(groupViewModel.UserIds, group);
				_context.Add(@group);
				await _context.SaveChangesAsync();
				TempData["Msg"] = groupViewModel.Name + " sucessfully added";
				return RedirectToAction(nameof(Index));
			}
			LoadFieldsViewModel(groupViewModel);
			return View(groupViewModel);
		}

		// GET: Groups/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var @group = await _context.Group
				.Include(x => x.Users)
				.FirstOrDefaultAsync(x => x.Id == id);
			if (@group == null)
			{
				return NotFound();
			}
			GroupViewModel viewModel = _mapper.Map<GroupViewModel>(group);
			LoadFieldsViewModel(viewModel);
			if (group.Users != null)
				viewModel.UserIds = group.Users.Select(x => x.UserId.ToString());
			return View(viewModel);
		}

		// POST: Groups/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name, UserIds")] GroupViewModel groupViewModel)
		{
			if (id != groupViewModel.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					Group group = _mapper.Map<Group>(groupViewModel);
					PopulateModelWithSelectedValues(groupViewModel.UserIds, group);

					//remove old groupuser dependency
					_context.GroupUser.RemoveRange(_context.GroupUser.Where(x => x.GroupId == id));
					await _context.SaveChangesAsync();

					_context.Update(@group);
					await _context.SaveChangesAsync();
					TempData["Msg"] = groupViewModel.Name + " sucessfully updated";
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!GroupExists(groupViewModel.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			LoadFieldsViewModel(groupViewModel);
			return View(groupViewModel);
		}

		// GET: Groups/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var @group = await _context.Group
				.Include(x => x.Users)
					.ThenInclude(y => y.User)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (@group == null)
			{
				return NotFound();
			}
			GroupViewModel viewModel = _mapper.Map<GroupViewModel>(group);
			return View(viewModel);
		}

		// POST: Groups/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var @group = await _context.Group.FindAsync(id);
			_context.Group.Remove(@group);
			await _context.SaveChangesAsync();
			TempData["Msg"] = @group.Name + " sucessfully removed.";
			return RedirectToAction(nameof(Index));
		}

		private bool GroupExists(int id)
		{
			return _context.Group.Any(e => e.Id == id);
		}

		private void LoadFieldsViewModel(GroupViewModel viewModel)
		{
			viewModel.Users = _context.User.Select(x =>
						new SelectListItem
						{
							Value = x.Id.ToString(),
							Text = x.Name
						}).ToList();
		}
		private void PopulateModelWithSelectedValues(IEnumerable<string> userIds, Group group)
		{
			foreach (string item in userIds)
			{
				GroupUser userGroup = new GroupUser();
				userGroup.User = _context.User.FirstOrDefault(x => x.Id == Convert.ToInt32(item));
				group.Users.Add(userGroup);
			}
		}
	}
}

Controllers/ServersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CertificatesManager.Database;
using CertificatesManager.Models;

namespace CertificatesManager.Controllers
{
    public class ServersController : Controller
    {
        private readonly CertificatesManagerDBContext _context;

        public ServersController(CertificatesManagerDBContext context)
        {
            _context = context;
        }

        // GET: Servers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Server.ToListAsync());
        }

        // GET: Servers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Server
                .FirstOrDefaultAsync(m => m.Id == id);
            if (server == null)
            {
                return NotFound();
            }

            return View(server);
        }

        // GET: Servers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Server server)
        {
            if (ModelState.IsValid)
            {
                _context.Add(server);
                await _context.SaveChangesAsync();
				TempData["Msg"] = server.Name + " sucessfully added";
				return RedirectToAction(nameof(Index));
            }
            return View(server);
        }

        // GET: Servers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Server.FindAsync(id);
            if (server == null)
            {
                return NotFound();
            }
            return View(server);
        }

        // POST: Servers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Server server)
        {
            if (id != server.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(server);
                    await _context.SaveChangesAsync();
					TempData["Msg"] = server.Name + " sucessfully updated";
				}
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServerExists(server.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(server);
        }

        // GET: Servers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Server
                .FirstOrDefaultAsync(m => m.Id == id);
            if (server == null)
            {
                return NotFound();
            }

            return View(server);
        }

        // POST: Servers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var server = await _context.Server.FindAsync(id);
            _context.Server.Remove(server);
            await _context.SaveChangesAsync();
			TempData["Msg"] = server.Name + " sucessfully removed";
			return RedirectToAction(nameof(Index));
        }

        private bool ServerExists(int id)
        {
            return _context.Server.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CertificatesManager.Database;
using CertificatesManager.Models;

namespace CertificatesManager.Controllers
{
    public class UsersController : Controller
    {
        private readonly CertificatesManagerDBContext _context;

        public UsersController(CertificatesManagerDBContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,PhoneExtension,IsAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
				TempData["Msg"] = user.Name + " sucessfully added";
				return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,PhoneExtension,IsAdmin")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
					TempData["Msg"] = user.Name + " sucessfully updated";
				}
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
			TempData["Msg"] = user.Name + " sucessfully removed";
			return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CertificatesManager</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
		<link rel="stylesheet" href="~/css/bootstrap-select.min.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
	<link href="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CertificatesManager</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Certificates" asp-action="Index">Certificates</a></li>
					<li><a asp-area="" asp-controller="Certificates" asp-action="Create">Upload</a></li>
					<li><a asp-area="" asp-controller="Servers" asp-action="Index">Servers</a></li>
					<li><a asp-area="" asp-controller="Applications" asp-action="Index">Applications</a></li>
					<li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
					<li><a asp-area="" asp-controller="Groups" asp-action="Index">Groups</a></li>
					<li><a asp-area="" asp-controller="Settings" asp-action="Index">Settings</a></li>
					<li><a href="hangfire">Email Scheduler</a></li>
				</ul>
			</div>
		</div>
	</nav>

	<partial name="_CookieConsentPartial" />

	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2019 - EirGrid CertificatesManager</p>
		</footer>
	</div>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/js/bootstrap-select.min.js"></script>
		<script src="~/js/highcharts.src.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
		<script src="https://unpkg.com/jquery-resizable-columns@0.2.3/dist/jquery.resizableColumns.min.js"></script>
	</environment>
	<script src="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/store.js/1.3.14/store.min.js"></script>

	@RenderSection("Scripts", required: false)
</body>
</html>